---
name: movix
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  blurrycontainer: ^0.0.1
  bubbled_navigation_bar: ^0.0.3
  cloud_firestore: ^0.16.0
  cupertino_icons: ^0.1.3
  dartz: ^0.9.2
  email_validator: ^1.0.4
  equatable: ^1.1.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  flushbar: ^1.10.0
  flutter_bloc: ^3.2.0
  flutter_spinkit: ^4.1.2+1
  google_fonts: ^1.1.2
  http: ^0.12.0+4
  image_picker: ^0.6.4
  intl: ^0.16.1
  material_design_icons_flutter: ^4.0.5855
  provider: ^4.0.4
  random_string: ^2.1.0
  shimmer: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
